//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Twitter
    {
        public System.Guid Id { get; set; }
        public string CRMUrl { get; set; }
        public string PublisherName { get; set; }
        public string SocialMediaType { get; set; }
        public string Row_Id { get; set; }
        public string UserID { get; set; }
        public string OauthToken { get; set; }
        public string OauthTokenSecret { get; set; }
        public string ScreenName { get; set; }
        public string Image_Url { get; set; }
        public System.DateTime AuthenticateDate { get; set; }
    }
}
