//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Database
{
    using System;
    using System.Collections.Generic;
    using System.Data.SqlTypes;
    public partial class tbl_Configuration
    {
        public System.Guid Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Company { get; set; }
        public string ContactNo { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string OrgUniqueName { get; set; }
        public string ServerUrl { get; set; }
        public string SubscriptionType { get; set; }
        public System.DateTime CreateDate { get; set; }       
        public System.DateTime ModifyDate { get; set; }
        public System.DateTime ExpireDate { get; set; }
    }
}
